DROP TYPE IF EXISTS grocery;

CREATE TYPE grocery AS ENUM(
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);

DROP TABLE IF EXISTS shopping_list;

CREATE TABLE shopping_list(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT,
    price DECIMAL(30, 2),
    date_added DATE DEFAULT now(),
    checked BOOLEAN DEFAULT false,
    category grocery
);